CREATE DATABASE `namedatabase`;

CREATE TABLE `namedatabase`.`commentaires` (
  `COMMENTAIRE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `COMMENTAIRE_ID_USER` int(11) NOT NULL,
  `COMMENTAIRE_ID_RECETTE` int(11) NOT NULL,
  `COMMENTAIRE_DATE` date NOT NULL,
  `COMMENTAIRE_CONTENU` text NOT NULL,
  PRIMARY KEY (`COMMENTAIRE_ID`,`COMMENTAIRE_ID_USER`,`COMMENTAIRE_ID_RECETTE`),
  KEY `COMMENTAIRE_ID_USER` (`COMMENTAIRE_ID_USER`),
  KEY `COMMENTAIRE_ID_RECETTE` (`COMMENTAIRE_ID_RECETTE`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

CREATE TABLE `namedatabase`.`etapes` (
  `ETAPE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `RECETTE_ID_ETAPE` int(11) NOT NULL,
  `ETAPE_INSTRUCTION` text NOT NULL,
  PRIMARY KEY (`ETAPE_ID`,`RECETTE_ID_ETAPE`),
  KEY `RECETTE_ID_ETAPE` (`RECETTE_ID_ETAPE`)
) ENGINE=InnoDB AUTO_INCREMENT=75 DEFAULT CHARSET=utf8;

CREATE TABLE `namedatabase`.`ingredients` (
  `INGREDIENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `INGREDIENT_NOM` varchar(35) NOT NULL,
  PRIMARY KEY (`INGREDIENT_ID`),
  UNIQUE KEY `idx_ingredient_nom` (`INGREDIENT_NOM`)
) ENGINE=InnoDB AUTO_INCREMENT=54 DEFAULT CHARSET=utf8;

CREATE TABLE `namedatabase`.`recettes` (
  `RECETTE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `RECETTE_TYPE` varchar(13) DEFAULT NULL,
  `RECETTE_TITRE` varchar(128) NOT NULL,
  `RECETTE_PHOTO` varchar(255) DEFAULT NULL,
  `RECETTE_VISIBILITE` tinyint(1) NOT NULL DEFAULT '0',
  `USER_ID_RECETTE` int(11) NOT NULL,
  PRIMARY KEY (`RECETTE_ID`),
  KEY `USER_ID_RECETTE` (`USER_ID_RECETTE`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8;

CREATE TABLE `namedatabase`.`recettes_ingredients` (
  `RECETTE_INGREDIENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `RECETTE_INGREDIENT_ID_RECETTE` int(11) NOT NULL,
  `RECETTE_INGREDIENT_ID_INGREDIENT` int(11) NOT NULL,
  `RECETTE_INGREDIENT_QUANTITE` varchar(8) NOT NULL,
  `RECETTE_INGREDIENT_ID_MESURE` int(11) NOT NULL,
  PRIMARY KEY (`RECETTE_INGREDIENT_ID`,`RECETTE_INGREDIENT_ID_RECETTE`),
  KEY `RECETTE_INGREDIENT_ID_RECETTE` (`RECETTE_INGREDIENT_ID_RECETTE`),
  KEY `RECETTE_INGREDIENT_ID_INGREDIENT` (`RECETTE_INGREDIENT_ID_INGREDIENT`),
  KEY `RECETTE_INGREDIENT_ID_MESURE` (`RECETTE_INGREDIENT_ID_MESURE`)
) ENGINE=InnoDB AUTO_INCREMENT=90 DEFAULT CHARSET=utf8;

CREATE TABLE `namedatabase`.`unites_mesure` (
  `UNITE_MESURE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `UNITE_MESURE_NOM` varchar(10) NOT NULL,
  PRIMARY KEY (`UNITE_MESURE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=utf8;

INSERT INTO `unites_mesure` (`UNITE_MESURE_ID`, `UNITE_MESURE_NOM`) VALUES
(1, 'L'),
(2, 'cl'),
(3, 'ml'),
(4, 'Kg'),
(5, 'g'),
(6, 'mg'),
(7, 'c.à.s'),
(8, 'c.à.c'),
(9, ''),
(10, 'paquet(s)'),
(11, 'cube(s)'),
(12, 'pincée'),
(13, 'poignée(s)'),
(14, 'tasse(s)'),
(15, 'pot(s)'),
(16, 'zeste'),
(17, 'gousse'),
(18, 'feuille(s)'),
(19, 'extrait');

CREATE TABLE `namedatabase`.`users` (
  `USER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_NOM` varchar(64) NOT NULL,
  `USER_PRENOM` varchar(64) NOT NULL,
  `USER_AGE` date NOT NULL,
  `USER_EMAIL` varchar(60) NOT NULL,
  `USER_HASH` varchar(255) NOT NULL,
  `USER_PHOTO` varchar(255) DEFAULT NULL,
  `TOKEN` int(11) DEFAULT NULL,
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

ALTER TABLE `commentaires`
  ADD CONSTRAINT `commentaires_ibfk_1` FOREIGN KEY (`COMMENTAIRE_ID_USER`) REFERENCES `users` (`USER_ID`),
  ADD CONSTRAINT `commentaires_ibfk_2` FOREIGN KEY (`COMMENTAIRE_ID_RECETTE`) REFERENCES `recettes` (`RECETTE_ID`);

ALTER TABLE `etapes`
  ADD CONSTRAINT `etapes_ibfk_1` FOREIGN KEY (`RECETTE_ID_ETAPE`) REFERENCES `recettes` (`RECETTE_ID`);

ALTER TABLE `recettes`
  ADD CONSTRAINT `recettes_ibfk_1` FOREIGN KEY (`USER_ID_RECETTE`) REFERENCES `users` (`USER_ID`);

ALTER TABLE `recettes_ingredients`
  ADD CONSTRAINT `recettes_ingredients_ibfk_1` FOREIGN KEY (`RECETTE_INGREDIENT_ID_RECETTE`) REFERENCES `recettes` (`RECETTE_ID`),
  ADD CONSTRAINT `recettes_ingredients_ibfk_2` FOREIGN KEY (`RECETTE_INGREDIENT_ID_INGREDIENT`) REFERENCES `ingredients` (`INGREDIENT_ID`),
  ADD CONSTRAINT `recettes_ingredients_ibfk_3` FOREIGN KEY (`RECETTE_INGREDIENT_ID_MESURE`) REFERENCES `unites_mesure` (`UNITE_MESURE_ID`);
COMMIT;


